Environment:
	Python: 3.8.11
	PyTorch: 1.8.1+cu111
	Torchvision: 0.9.1+cu111
	CUDA: 11.1
	CUDNN: 8005
	NumPy: 1.21.2
	PIL: 8.3.1
Args:
	algorithm: ERM_ViT_DeiT
	checkpoint_freq: None
	data_dir: /home/computervision1/DG_new_idea/domainbed/data/
	dataset: PACS
	holdout_fraction: 0.2
	hparams: {"batch_size":32,"lr":5e-05,"resnet_dropout":0.0,"weight_decay":0.0}
	hparams_seed: 0
	output_dir: ./domainbed/Accross_Datasets/PACS/7d57fb0710b8dce0ff9f334c273b6d40
	save_best_model: True
	save_model_every_checkpoint: False
	seed: 1927005543
	skip_model_save: False
	steps: None
	task: domain_generalization
	test_envs: [2]
	trial_seed: 2
	uda_holdout_fraction: 0
HParams:
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: False
	resnet_dropout: 0.0
	test_env: [2]
	weight_decay: 0.0
device: cuda
Traceback (most recent call last):
  File "/home/computervision1/anaconda3/envs/dgbed/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/computervision1/anaconda3/envs/dgbed/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/computervision1/Maryam/ViT-self-dist-DG/domainbed/scripts/train.py", line 190, in <module>
    algorithm = algorithm_class(dataset.input_shape, dataset.num_classes,
  File "/home/computervision1/Maryam/ViT-self-dist-DG/domainbed/algorithms.py", line 329, in __init__
    self.network = torch.hub.load('./domainbed/pretrained_models/DeiT_models', 'deit_small_patch16_224',
  File "/home/computervision1/anaconda3/envs/dgbed/lib/python3.8/site-packages/torch/hub.py", line 339, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/computervision1/anaconda3/envs/dgbed/lib/python3.8/site-packages/torch/hub.py", line 365, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "/home/computervision1/anaconda3/envs/dgbed/lib/python3.8/site-packages/torch/hub.py", line 74, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: './domainbed/pretrained_models/DeiT_models/hubconf.py'
